version: 0.2

phases:
  install:
    commands :
      - echo Entered the install phase...
      - apt-get update -y
      - apt-get install -y maven
    runtime-versions:
        java: corretto17     
  build:
    commands:
      - echo Build Starting on `date`
      - mvn install
      - mvn package
  post_build:
    commands:
      - echo Entered the post_build phase
      - chmod +x scripts/**
artifacts:
  files:
    - target/*.jar
    - appspec.yml
    - scripts/**
  discard-paths: yes
cache:
  paths:
    - '/root/.m2/**/*'